### ISSUE TITLE
Cody style review

### ISSUE THREAD

**Issue by xrem** [FRedEnergy/itmo-oop-tasks#1]
**Code style style action items:**
1) Do not omit brackets when creating one-line loops, methods and so on.
![image](https://user-images.githubusercontent.com/7121898/64905111-f0582080-d6db-11e9-8a40-8262199072bf.png)
![image](https://user-images.githubusercontent.com/7121898/64905173-ee429180-d6dc-11e9-9a5f-562063714b25.png)

**Optional code style action items:**
1) Please remove redundant blank project from solution
![image](https://user-images.githubusercontent.com/7121898/64905005-b9cdd600-d6da-11e9-8573-477bf6454afa.png)

2) There are unnecessary whitespaces in your files.
Enable following option in your Rider: 
`Settings | Editor | General | Appearance | Show whitespace`
And set `Code Inspection: Unnecessary whitespace` notifications level to warning.
![image](https://user-images.githubusercontent.com/7121898/64905077-9b1c0f00-d6db-11e9-85c6-c0c80e9a6803.png)

3) You could use expression-bodies properties instead of this:
![image](https://user-images.githubusercontent.com/7121898/64905160-d408b380-d6dc-11e9-8d19-cf92c01871c8.png)
![image](https://user-images.githubusercontent.com/7121898/64905162-d9fe9480-d6dc-11e9-9c8a-150edacfd9ba.png)

**Comment by abvadabra** [comment]
Fixed everything except one-line loops and if's in d8fdbab7303ef5934d49b6e8dc698423c0b1567c
