### ISSUE TITLE
Music catalog search engine issues.

### ISSUE THREAD

**Issue by xrem** [FRedEnergy/itmo-oop-tasks#2]
There is a `TrackGroup` class created but was not used, please implement `ISearchable` interface for `TaskGroup`s too, since it's a task requirement.

All fields of `SearchQuery` class should be private. 
Fields `IncludeTracks, IncludeAlbums, IncludeArtists` may be converted to auto-properties,
Something like this: 
```c#
public bool IncludeTracks { get; private set; }
```
Also, do not ignore your IDE hints:
![image](https://user-images.githubusercontent.com/7121898/64917772-bac73c00-d79c-11e9-8f58-16cca4cc5af9.png)

There is another requirement in the task: `Track must not be exists without album`, but I can break this logic if i'll call the following statements: 
```c#
var genre = new Genre("Rock");
var artist = new Artist("My Band", genre);
var track = new Track(artist, null, "Track#01");
```

`Catalog`'s Artists field should not be public since it's an encapsulation rule violation.
Please review other classes for the same issues.

It would be awesome, if you can make `Catalog` class static.
That would allow us to register all `ISearchable` objects in the catalog right after initialization.

**Comment by abvadabra** [comment]
Pushed 19629644271005df42d5bb5557e4bb61c20c9a03 with fixes for this issues

I made all fields in SearchQuery private to fix encapsulation and added private setters for Include* fields
![image](https://user-images.githubusercontent.com/8457835/65411953-db277400-ddf6-11e9-8e65-fcfc7007ed57.png)

Class TrackGroup now is called Playlist and can contain tracks from multiple artists, also Catalog now has a list of Playlists which can be searched by name.

Track's constructor is now internal and Album class now acts as a factory for creating tracks 
![image](https://user-images.githubusercontent.com/8457835/65411667-16757300-ddf6-11e9-99a5-8b3bf8b13a30.png)
In track's constructor I added arguments validation to ensure that it's not possible to provde null artist or album
![image](https://user-images.githubusercontent.com/8457835/65411704-386ef580-ddf6-11e9-9591-3a99d4b618b3.png)

I also has fixed encapsulation in Playlist by making tracks list private and exposing only ReadOnlyColleciton of tracks
![image](https://user-images.githubusercontent.com/8457835/65411813-871c8f80-ddf6-11e9-9e82-a8efa5dfe60e.png)

Catalog class is now static with all it's content initialized in static constructor
![image](https://user-images.githubusercontent.com/8457835/65411886-b3381080-ddf6-11e9-9ac2-412db6a8e23a.png)

I also fixed some minor issues in that commit e.g. properly implemented ToString in Artist, Playlist, Album and Track classes.
